story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = "story8"

urlpatterns = [
    path('', views.index, name='index'),
    path('cari/', views.search, name='search'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
]

story_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls')),
    path('story-8/', include('story8.urls')),
    path('story-7/', include('story7.urls')),
]

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username', 'password1', 'password2']

story7/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story7/accordion.html')

story8/views.py
from django.http import response
from django.shortcuts import render
from django.http import JsonResponse
import requests, json

def index(request):
    response = {}
    return render(request, 'story8/bookfinder.html', response)

def search(request):
    arg = request.GET['q']
    link = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(link)
    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm

def home(request):
    return render(request, 'story9/welcome.html')

def user_login(request):
    if request.method == "POST":
        username_input = request.POST["username"]
        password_input = request.POST["password"]

        user = authenticate(request, username=username_input, password=password_input)

        if user is not None:
            login(request, user)
            return redirect('story9:home')

    return render(request, 'story9/login.html')

def user_logout(request):
    if request.method == "POST":
        if request.POST["logout"] == "Logout":
            logout(request)
            return redirect('story9:home')

    return render(request, 'story9/logout.html')

def user_signup(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story9:login')
    context = {'form' : form}
    return render(request,'story9/signup.html', context)

story7/templates/story7/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story7/style_story7.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'story7/styling7.js' %}"></script>
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
  <div class="judul">
    <h2>Click Each Card To Get To Know Me 🍋</h2>
    <hr>
  </div>
  <div class="accordion">
    <div class="card">
      <div class="card-header head">
          <h3 class="accordion-title">Lemon's Daily Activities</h3>
          <i class="fa fa-arrow-circle-up switch"  id="up" data-sort="up"></i>
          <i class="fa fa-arrow-circle-down switch" id="down" data-sort="down"></i>
      </div>
      <div class="card-body" >
        <ul class>
          <li id="kegiatan">Kuliah</li>
          <li id="kegiatan">Begadang Nugas</li>
          <li id="kegiatan">Overthinking Semester 3 Bisa Lulus Ngga Ya?</li>
        </ul>
      </div>
    </div>
  
    <div class="card">
      <div class="card-header head">
          <h3 class="accordion-title">Lemon's Experiences</h3>
          <i class="fa fa-arrow-circle-up switch"  id="up" data-sort="up"></i>
          <i class="fa fa-arrow-circle-down switch" id="down" data-sort="down"></i>
      </div>
      <div class="card-body" >
        <ul class>
          <li id="pengalaman">BETIS 2019 Staff Akademis</li>
          <li id="pengalaman">Udah ngga ada lagi anaknya emang kurang aktif bund,, mmf</li>
        </ul>
      </div>
    </div>
  
    <div class="card">
      <div class="card-header head">
          <h3 class="accordion-title">Lemon's Achievements</h3>
          <i class="fa fa-arrow-circle-up switch"  id="up" data-sort="up"></i>
          <i class="fa fa-arrow-circle-down switch" id="down" data-sort="down"></i>
      </div>
      <div class="card-body" >
        <ul class>
          <li id="prestasi">Terakhir juara LCC PAI tingkat kota/kabupaten pas SMP itu juga</li>
          <li id="prestasi">Mandi sehari sekali selama PJJ</li>
          <li id="prestasi">Tahan berbulan-bulan ga keluar rumah</li>
        </ul>
      </div>
    </div>
  
    <div class="card">
      <div class="card-header head">
          <h3 class="accordion-title">Songs Lemon Listen To These Days</h3>
          <i class="fa fa-arrow-circle-up switch"  id="up" data-sort="up"></i>
          <i class="fa fa-arrow-circle-down switch" id="down" data-sort="down"></i>
      </div>
      <div class="card-body" >
        <ul class>
          <li id="lagu">Come Inside Of My Heart - IV Of Spades</li>
          <li id="lagu">Good Day - Surfaces</li>
          <li id="lagu">Pluto Projector - Rex Orange County</li>
          <li id="lagu">Don't Wanna Fall in Love Again - Yayyoung</li>
        </ul>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

story8/templates/story8/bookfinder.html
{% extends 'base.html' %}
{% load static %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story8/style_story8.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
<script src="{% static 'story8/styling8.js' %}"></script>
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
    <div class="judul">
        <h2>Cari Buku Disini</h2>
        <hr>
    </div>

    <div class="input-group mb-3 col-sm-6">
        <input type="text" class="form-control" id="inputan" placeholder="Ketik buku yang ingin dicari" aria-label="Ketik buku yang ingin dicari" aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-outline-success" type="button" id="search">Cari</button>
        </div>
    </div>
    
    <div class="tabel">
        <table class="table table-hover table-bordered">
            <thead class="thead-dark" id="header">
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Judul</th>
                <th scope="col">Penulis</th>
                <th scope="col">Penerbit</th>
                <th scope="col">Sampul Buku</th>
              </tr>
            </thead>

            <tbody id="buku">
                <!-- {% for d in data %}
                    {% for buku in d.items %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{buku.volumeInfo.title}}</td>
                            <td>{{buku.volumeInfo.authors}}</td>
                            <td>{{buku.volumeInfo.publisher}}</td>
                        </tr>
                    {% endfor %}
                {% endfor %} -->
            </tbody>
        </table>
    </div>

</div>


{% endblock content %}

story9/templates/story9/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login Page{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story9/style_story9.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
    <div class="login">
        <h2 id="title">Login Here</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="row mb-3 inputan">
                <label for="inputUsername" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-6">
                  <input type="text" class="form-control" name="username" id="inputUsername">
                </div>
            </div>
            <div class="row mb-3 inputan">
                <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-6">
                  <input type="password" class="form-control" name="password" id="inputPassword">
                </div>
            </div>
            {{ form.errors }}
            <div class="tombol">
                <button type="submit" name="login" class="btn btn-success">Login</button>
                <a href="{% url 'story9:signup' %}" class="btn btn-warning">Sign Up</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

story9/templates/story9/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Logout Page{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story9/style_story9.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
    <div class="logout">
        <div class="card text-center">
            <div class="card-header">
              <h3>Logout</h3>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{ user.get_username }} yakin ingin logout? 😔</h5>
              <form method="POST">
                {% csrf_token %}
                <input type="submit" name="logout" value="Logout" class="btn btn-danger tombol">
            </form>
            </div>
          </div>
        </div>
    </div>
    
</div>
{% endblock content %}

story9/templates/story9/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Signup Page{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story9/style_story9.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
    <div class="signup">
        <h2 id="title">Sign Up Here</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="row mb-3 inputan">
                <label for="inputUsername" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                  {{ form.username }}
                </div>
            </div>
            <div class="row mb-3 inputan">
                <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  {{ form.password1 }}
                </div>
            </div>
            <div class="row mb-3 inputan">
                <label for="inputPassword" class="col-sm-2 col-form-label">Confirm Password</label>
                <div class="col-sm-10">
                  {{ form.password2 }}
                </div>
            </div>
            {{ form.errors }}
            <div class="tombol">
                <button type="submit" name="signup" class="btn btn-success">Sign Up</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

story9/templates/story9/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Page{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'story9/style_story9.css' %}"> 
{% endblock additional_css %}

{% block additional_script %}
{% endblock additional_script %}

{% block content %}
<div class="container-fluid">
    <div class="home">
        <h1>Welcome to Lemon's Website</h1>
        <hr>
        {% if user.is_authenticated %}
        <h3>Halo, {{user.get_username}}! 😊</h3>
        {% else %}
        <h3>Belum Login?</h3>
        <a class="btn btn-outline-dark mt-2" href="{% url 'story9:login' %}">Login</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Story 7{% endblock title %}</title>
  
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block additional_css %}
  {% endblock additional_css %}

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {% block additional_script %}
  {% endblock additional_script %}
</head>

<body>
  <div class="menu-bar">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <img src="{% static 'img/lemon (2).png' %}">
      <a class="navbar-brand" href="#">Lela Monica</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-link" href="{% url 'story9:home' %}">Home</a>
          <a class="nav-link" href="{% url 'story7:index' %}">Story 7</a>
          <a class="nav-link" href="{% url 'story8:index' %}">Story 8</a>
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'story9:logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'story9:login' %}">Login</a>
          <a class="nav-link" href="{% url 'story9:signup' %}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </div>

  {% block content %}
  {% endblock content %}
</body>

</html>